### ISSUE TITLE
Add camera functionality 

### ISSUE THREAD

**Issue by matiasandina** [matiasandina/FEDWatcher#30]
The idea is to have the ability to respond to events by recording them to video.
We would have a camera initialized continuously dumping frames to a queue.
We would trigger the camera with actions that tell it to start recording and to stop recording.
The recording will happen with a buffer before the start signal is given. 
The stop signal can be a `finish()` that flushes the whole queue. We don't have to have symmetrical buffers.
**Note, the current implementation is for one fed and one camera.** 
---
There are a two classes that allow us to do this. One is the `VideoFeedClipper` (handle video and timestamping, pass frames to queues in the writer), and the other one is the `KeyClipWriter` (actually do the write).
 
It remains to be seen how/where to add this to `fedwatcher.py` itself. 

We could use the `f` argument of the `run` function to give a function that processes the incoming line and decides whether it's a start or a stop signal.

### TODO:

- [ ] add `with_video` argument to fedwatcher.py init
- [ ] `with_video` should initialize the VideoFeedClipper.py 
  * if we don't pay the cost at the init, we will pay the cost of initializing cameras in the middle of the action
  * but should this be a separate thread?
- [ ] figure out a way to efficiently read the event type. is  `readPort` the best place to do this? it is the place with `f()`
- [ ] pass event type to a function that will determine if the event type needs to trigger or stop recording

**Comment by matiasandina** [comment]
Any suggestions @RedSweatshirt  ?
